# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import app.messages.messages_pb2 as messages__pb2


class VideoProcessorStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetVideoAnalysis = channel.stream_stream(
                '/VideoProcessor/GetVideoAnalysis',
                request_serializer=messages__pb2.ImageRequest.SerializeToString,
                response_deserializer=messages__pb2.ImageResponse.FromString,
                )


class VideoProcessorServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetVideoAnalysis(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_VideoProcessorServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetVideoAnalysis': grpc.stream_stream_rpc_method_handler(
                    servicer.GetVideoAnalysis,
                    request_deserializer=messages__pb2.ImageRequest.FromString,
                    response_serializer=messages__pb2.ImageResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'VideoProcessor', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class VideoProcessor(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetVideoAnalysis(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(request_iterator, target, '/VideoProcessor/GetVideoAnalysis',
            messages__pb2.ImageRequest.SerializeToString,
            messages__pb2.ImageResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
